name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/**'    # Update path to match your repo
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./Backend     # Updated path
        file: ./Backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/sarthi-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/sarthi-backend:${{ github.sha }}
