name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/**'    # Only trigger when Backend code changes
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/**'    # Only trigger on PRs affecting Backend code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4

    # Authenticate with Docker Hub using repository secrets
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build the Docker image and push to Docker Hub
    # Uses two tags: 'latest' for most recent version and commit SHA for versioning
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./Backend     # Set build context to Backend directory
        file: ./Backend/Dockerfile  # Location of Dockerfile
        push: true             # Push image to registry after building
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/sarthi-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/sarthi-backend:${{ github.sha }}
